# code: language=ansible

ssh:
  # group: ssh
  name: local-test-2ssh
  dir: "{{ ssh_dir }}"
  approve_task: "{{ playbook_dir }}/../seed-ssh.approve/seed-ssh.test.yml"
  config_path: "{{ ssh_dir }}/config"
  known_path: "{{ ssh_dir }}/known_hosts"
  known_hash: true
  known_scan:
    - 'ecdsa-sha2-nistp256'
    - 'ssh-ed25519'
    - 'ssh-rsa'

docker:
  package:
    - sshpass
    - rsync
    - git
  pip:
    - jsondiff==2.0.0
    - jmespath==1.0.1
    # bug for https://github.com/yaml/pyyaml/issues/724
    - PyYAML==5.3.1
    - lxml==4.9.2
    # bug for https://github.com/docker/docker-py/issues/3113
    - requests==2.28.1
