# code: language=ansible

ssh:
  # group: ssh
  name: local-test-2ssh
  dir: "~/../..{{ hostvars['localhost'].ssh_dir }}"
  keyscan_types:
    - 'ecdsa-sha2-nistp256'
    - 'ssh-ed25519'
    - 'ssh-rsa'
  approve_task: "{{ playbook_dir }}/../seed-ssh.approve/seed-ssh.test.yml"
  known_path: "{{ hostvars['localhost'].ssh_dir }}/known_hosts"
  known_names:
    - "[{{ ansible_host | default(inventory_hostname,true) }}]:22221"
    - "[mock_ssh_server]:22221"
    - "[192.168.86.1]:22221"
  config_path: "{{ hostvars['localhost'].ssh_dir }}/config"

docker:
  package:
    - sshpass
    - rsync
    - git
  pip:
    - jsondiff==2.0.0
    - jmespath==1.0.1
    # bug for https://github.com/yaml/pyyaml/issues/724
    - PyYAML==5.3.1
    - lxml==4.9.2
    # bug for https://github.com/docker/docker-py/issues/3113
    - requests==2.28.1

system:
  # group: docker
  # init_task: "{{ playbook_dir }}/../ansible-tasks/seed-docker.init.yml"
