# code: language=ansible

all:
  hosts:
    # fix inventory_dir is undefined https://github.com/ansible/ansible/issues/31087
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3

  children:
    wsl:
      hosts:
        localhost:
