# code: language=ansible
---

- name: docker-stack.deploy|fact workpath
  when: workpath.remote is undefined
  include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-workpath.fact.yml"

- name: docker-stack.deploy|assert compose
  ansible.builtin.assert:
    that:
      - stack is defined
    msg: "var eval fail {{ stack }}"
    quiet: true

- name: docker-stack.deploy|fact param
  ansible.builtin.set_fact:
    _stack_deploy: "{{ stack }}"

- name: docker-stack.deploy|include vars
  vars:
    vars_file: "{{
      _stack_deploy.override.vars_file | default(None) or 
      _stack_deploy.vars_file | default(None) or
      '' }}"
  when: vars_file != ''
  ansible.builtin.include_vars:
    file: "{{ vars_file }}"

- block:
  - name: docker-stack.deploy|mkdir workpath
    ansible.builtin.file:
      state: directory
      path: "{{ workpath.remote.full }}"

  - name: docker-stack.deploy|push files
    when: files | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-files.push.yml"
    vars:
      files: "{{
        _stack_deploy.override.files | default(None) or 
        _stack_deploy.files | default(None) or
        [] }}"
      files_share: "{{
        _stack_deploy.override.share.files | default(None) or 
        _stack_deploy.share.files | default(None) or
        {} }}"

  - name: docker-stack.deploy|init nfs-mounts
    when: mounts | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-nfs/nfs-mounts.init.yml"
    vars:
      mounts: "{{
        _stack_deploy.override.mounts | default(None) or 
        _stack_deploy.mounts | default(None) or
        [] }}"
      mounts_share: "{{
        _stack_deploy.override.share.mounts | default(None) or 
        _stack_deploy.share.mounts | default(None) or
        {} }}"

  - name: docker-stack.deploy|init volumes
    when: volumes | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-volumes.init.yml"
    vars:
      volumes: "{{
        _stack_deploy.override.volumes | default(None) or 
        _stack_deploy.volumes | default(None) or
        [] }}"
      volumes_share: "{{
        _stack_deploy.override.share.volumes | default(None) or 
        _stack_deploy.share.volumes | default(None) or
        {} }}"

  - name: docker-stack.deploy|init networks
    when: networks | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-networks.init.yml"
    vars:
      networks: "{{
        _stack_deploy.override.networks | default(None) or 
        _stack_deploy.networks | default(None) or
        [] }}"
      networks_share: "{{
        _stack_deploy.override.share.networks | default(None) or 
        _stack_deploy.share.networks | default(None) or
        {} }}"

  - name: docker-stack.deploy|add configs
    when: configs | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-configs.add.yml"
    vars:
      configs: "{{
        _stack_deploy.override.configs | default(None) or 
        _stack_deploy.configs | default(None) or
        [] }}"
      configs_share: "{{
        _stack_deploy.override.share.configs | default(None) or 
        _stack_deploy.share.configs | default(None) or
        {} }}"

  - name: docker-stack.deploy|add secrets
    when: secrets | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-secrets.add.yml"
    vars:
      secrets: "{{
        _stack_deploy.override.secrets | default(None) or 
        _stack_deploy.secrets | default(None) or
        [] }}"
      secrets_share: "{{
        _stack_deploy.override.share.secrets | default(None) or 
        _stack_deploy.share.secrets | default(None) or
        {} }}"

  - name: docker-stack.deploy|add labels
    when: labels | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-labels.add.yml"
    vars:
      labels: "{{
        _stack_deploy.override.labels | default(None) or 
        _stack_deploy.labels | default(None) or
        [] }}"
      labels_share: "{{
        _stack_deploy.override.share.labels | default(None) or 
        _stack_deploy.share.labels | default(None) or
        {} }}"

  - name: docker-stack.deploy|push envs
    when: envs | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-envs.push.yml"
    vars:
      envs: "{{
        _stack_deploy.override.envs | default(None) or 
        _stack_deploy.envs | default(None) or
        [] }}"
      envs_share:
        mode: "{{
          _stack_deploy.override.share.envs.mode | default(None) or 
          _stack_deploy.share.envs.mode | default(None) or
          'value' }}"
        group: "{{
          _stack_deploy.override.share.envs.mode | default(None) or 
          _stack_deploy.share.envs.mode | default(None) or
          'docker-manager' }}"

  - name: docker-stack.deploy|push composes
    when: composes | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-composes.push.yml"
    vars:
      composes: "{{
        _stack_deploy.override.composes | default(None) or 
        _stack_deploy.composes | default(None) or
        [] }}"
      composes_share:
        mode: "{{
          _stack_deploy.override.share.composes.mode | default(None) or 
          _stack_deploy.share.composes.mode | default(None) or
          'value' }}"
        group: "{{
          _stack_deploy.override.share.composes.mode | default(None) or 
          _stack_deploy.share.composes.mode | default(None) or
          'docker-manager' }}"

  - name: docker-stack.deploy|add compose
    when: compose.files | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-compose.add.yml"
    vars:
      compose: 
        type: stack
        name: "{{ _stack_deploy.name | default(workpath.name,true) }}"
        path: "{{ _stack_deploy.path | default(workpath.remote.full,true) }}"
        files: "{{ (
          _stack_deploy.override.composes | default(None) or 
          _stack_deploy.composes | default(None) or
          []
          ) | map(attribute='file') }}"
      compose_share:
        group: "{{
          _stack_deploy.override.share.group | default(None) or 
          _stack_deploy.share.group | default(None) or
          'docker-manager' }}"
        once: "{{
          _stack_deploy.override.share.once | default(None) or 
          _stack_deploy.share.once | default(None) or
          false }}"
        any: "{{
          _stack_deploy.override.share.any | default(None) or 
          _stack_deploy.share.any | default(None) or
          true }}"

- name: docker-stack.deploy|unfact param
  run_once: true
  ansible.builtin.set_fact:
    _stack_deploy: !!null
