# code: language=ansible
---

- name: docker-container.deploy|fact workpath
  when: workpath.remote is undefined
  include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-workpath.fact.yml"

- name: docker-container.deploy|assert container
  ansible.builtin.assert:
    that:
      - container is defined
    msg: "var eval fail {{ container }}"
    quiet: true

- name: docker-container.deploy|fact param
  ansible.builtin.set_fact:
    _container_deploy: "{{ container }}"

- name: docker-container.deploy|include vars
  vars:
    vars_file: "{{
      _container_deploy.override.vars_file | default(None) or
      _container_deploy.vars_file | default(None) or
      '' }}"
  when: vars_file != ''
  ansible.builtin.include_vars:
    file: "{{ vars_file }}"

- block:
  - name: docker-container.deploy|mkdir workpath
    ansible.builtin.file:
      state: directory
      path: "{{ workpath.remote.full }}"

  - name: docker-container.deploy|push files
    when: files | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-files.push.yml"
    vars:
      files: "{{
        _container_deploy.override.files | default(None) or
        _container_deploy.files | default(None) or
        [] }}"
      files_share: "{{
        _container_deploy.override.share.files | default(None) or
        _container_deploy.share.files | default(None) or
        {} }}"

  - name: docker-container.deploy|init nfs-mounts
    when: mounts | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-nfs/nfs-mounts.init.yml"
    vars:
      mounts: "{{
        _container_deploy.override.mounts | default(None) or
        _container_deploy.mounts | default(None) or
        [] }}"
      mounts_share: "{{
        _container_deploy.override.share.mounts | default(None) or
        _container_deploy.share.mounts | default(None) or
        {} }}"

  - name: docker-container.deploy|init volumes
    when: volumes | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-volumes.init.yml"
    vars:
      volumes: "{{
        _container_deploy.override.volumes | default(None) or
        _container_deploy.volumes | default(None) or
        [] }}"
      volumes_share: "{{
        _container_deploy.override.share.volumes | default(None) or
        _container_deploy.share.volumes | default(None) or
        {} }}"

  - name: docker-container.deploy|init networks
    when: networks | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-networks.init.yml"
    vars:
      networks: "{{
        _container_deploy.override.networks | default(None) or
        _container_deploy.networks | default(None) or
        [] }}"
      networks_share: "{{
        _container_deploy.override.share.networks | default(None) or
        _container_deploy.share.networks | default(None) or
        {} }}"

  - name: docker-container.deploy|push envs
    when: envs | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-envs.push.yml"
    vars:
      envs: "{{
        _container_deploy.override.envs | default(None) or
        _container_deploy.envs | default(None) or
        [] }}"
      envs_share:
        mode: "{{
          _container_deploy.override.share.envs.mode | default(None) or
          _container_deploy.share.envs.mode | default(None) or
          'index' }}"
        group: "{{
          _container_deploy.override.share.envs.mode | default(None) or
          _container_deploy.share.envs.mode | default(None) or
          'docker' }}"

  - vars:
      container_var: "{{
        _container_deploy.override.container | default(None) or
        _container_deploy.container | default(None) or
        [] }}"
    when: container_var.image is defined
    block:
    - name: docker-container.deploy|run container
      become: "{{ _container_deploy.share.become | default(false) }}"
      vars:
        attr:
          name: "{{ _container_deploy.name | default(workpath.name,true) }}"
          labels:
            "com.github.xiaoyao9184.docker-seed.type": "docker-container.deploy"
            "com.github.xiaoyao9184.docker-seed.creator": "{{ lookup('ansible.builtin.env', 'SEED_NAME') | default('docker-container.deploy',true) }}"
        args: "{{ attr | combine(container_var, recursive=True) }}"
      community.docker.docker_container: "{{ args }}"

- name: docker-container.deploy|unfact param
  run_once: true
  ansible.builtin.set_fact:
    _container_deploy: !!null
