# code: language=ansible

all:
  hosts:
    node1:
      ansible_host: localhost
      ansible_connection: local
    node2:
      ansible_host: localhost
      ansible_connection: local
    node3:
      ansible_host: localhost
      ansible_connection: local
    node4:
      ansible_host: localhost
      ansible_connection: local

  children:
    linux:
      hosts:
        node1:
        node2:
        node3:
        node4:

    linux-34:
      hosts:
        node3:
        node4:
