# code: language=ansible

workspace:
  package:
    - sshpass
    - rsync
    - git
  pip:
    - jsondiff==2.0.0
    - jmespath==1.0.1
    # bug for https://github.com/yaml/pyyaml/issues/724
    - PyYAML==5.3.1
    - lxml==4.9.2
    # bug for https://github.com/docker/docker-py/issues/3113
    - requests==2.28.1

  local: "{{ host_path }}/../../../"
  # Simulate multiple host paths on localhost
  remote: "{{ playbook_dir }}/build/{{ inventory_hostname }}"
  unknow: "no change fact attribute defined by inventory {{ inventory_hostname }}"

workpath:
  index: -2
  unknow: "no change fact attribute defined by inventory {{ inventory_hostname }}"

ssh:
  name: none
  group: none

system:

docker:
  package:
    - sshpass
    - rsync
    - git
  pip:
    - jsondiff==2.0.0
    - jmespath==1.0.1
    # bug for https://github.com/yaml/pyyaml/issues/724
    - PyYAML==5.3.1
    - lxml==4.9.2
    # bug for https://github.com/docker/docker-py/issues/3113
    - requests==2.28.1
